[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  included_files = [".env"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"